### ISSUE TITLE
一些使用问题。

### ISSUE THREAD

**Issue by Joilence** [flexih/PNF#1]
1、似乎还不支持导出为视频？
2、另外「支持会员登录」请问在哪里可以登陆？

**Comment by flexih** [comment]
1.下载完的视频右键选择Show in Finder，能找到下载完成的视频文件，国内的视频网站基本都是分片的，可以在任一视频播放器里播放
2.下载管理列表选中一项右键选择以会员登录

**Comment by Joilence** [comment]
对于会员节目系列似乎还是不行。两个 Button 均无法按下。

**Comment by flexih** [comment]
> 两个 Button 均无法按下。

是说打开的网页里的button吧？

我修改一下。

**Comment by Joilence** [comment]
是的。但是不明白即使 Button 可以按下，似乎也不能进入登陆流程吧，那要如何才可以下载会员节目？
可以先试试buttom 我也不确定

-- Jonathan Yang
-- cjyk84719@gmail.com

**Comment by flexih** [comment]
可以的，在网页里登录完会有cookie，这样就能下载了。晚上我更新一下。

**Comment by Joilence** [comment]
好的。

-- Best Wishes
-- Jonathan Yang（杨竣然）
-- cjyk84719@gmail.com

**Comment by flexih** [comment]
https://raw.githubusercontent.com/flexih/PNF/master/downloader/1.1/ABUDownloader.zip

修复了

**Comment by Joilence** [comment]
会员节目下载问题成功解决。但关于分片依然希望 ABUDownloader 可以直接下载后合并为单个视频。

Google 「分片视频 合并」似乎没有其他软件解决方案，如果用非线性视频剪辑软件一个一个连接的话似乎有点过于麻烦，不如 ABUDownloader 直接下载合并。

是否下载后直接合并分片视频有比较大的技术难题？

-- Best Wishes
-- Jonathan Yang（杨竣然）
-- cjyk84719@gmail.com

**Comment by flexih** [comment]
合并分片也可以。不过目前没有时间点。

**Comment by flexih** [comment]
目前付费量太低了。。。

**Comment by Joilence** [comment]
呃说来我也还在试用期中...😥
不过下载会员节目的需求只是单纯的占有欲，如果需要手动连接分片觉得还是比较麻烦。
另一边可意视频 Supper 我已经购买会员了，能满足普通视频的下载，可能不太考虑这边的购买😓。
对于自动拼接的话可能我个人的购买意愿确实不足以提出这种要求，有点可惜。🙁

-- Best Wishes
-- Jonathan Yang（杨竣然）
-- cjyk84719@gmail.com

**Comment by flexih** [comment]
哈哈 没关系
